// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Person.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Game.JIT
{

    [global::ProtoBuf.ProtoContract(Name = @"S2C_Login")]
    public partial class S2CLogin : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"psw", IsRequired = true)]
        public string Psw { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"phones")]
        public global::System.Collections.Generic.List<LoginNumber> Phones { get; } = new global::System.Collections.Generic.List<LoginNumber>();

        [global::ProtoBuf.ProtoContract()]
        public partial class LoginNumber : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"number", IsRequired = true)]
            public string Number { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"type")]
            [global::System.ComponentModel.DefaultValue(S2CLogin.LoginType.C)]
            public S2CLogin.LoginType Type
            {
                get => __pbn__Type ?? S2CLogin.LoginType.C;
                set => __pbn__Type = value;
            }
            public bool ShouldSerializeType() => __pbn__Type != null;
            public void ResetType() => __pbn__Type = null;
            private S2CLogin.LoginType? __pbn__Type;

        }

        [global::ProtoBuf.ProtoContract()]
        public enum LoginType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"a")]
            A = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"b")]
            B = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"c")]
            C = 2,
        }

    }

    [global::ProtoBuf.ProtoContract(Name = @"s2c_login_all")]
    public partial class S2cLoginAll : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"s2c_login")]
        public global::System.Collections.Generic.List<S2CLogin> S2cLogins { get; } = new global::System.Collections.Generic.List<S2CLogin>();

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
